### PR TITLE
Executor Base Class for Reduce; ++buffer

### PR DESCRIPTION
**Pull request by WesRoach**
Tested with `make run-dflag`.

1. Inheritance via `Executor`
2. Potential Base class `Executor.hpp` with shared attributes and a potentially polymorphic function `toString` but 🤷 
3. Added a buffer

### CODE REVIEW

**Comment by josephcranston** [comment]
After reading a bit online, the alternative approach you suggested may not work because a member function template cannot be virtual. But the current approach with Executor being a base template class seems to work and implements both templates and inheritance, and I was able to apply similar changes to Map class and things are running smoothly.

**Comment by josephcranston** [comment]
Is there any reason you renamed your reduce() method to execute() if we're not using the pure virtual execute() method in the base class? Also should we add a base class pointer to derived class object to Workflow.cpp to call the virtual toStirng() method to demonstrate polymorphism?

**Comment by WesRoach** [comment]
@josephcranston 

> Is there any reason you renamed your reduce() method to execute() if we're not using the pure virtual execute() method in the base class? 

Left it as execute to be more generic, but other than that - nope!

> Also should we add a base class pointer to derived class object to Workflow.cpp to call the virtual toStirng() method to demonstrate polymorphism?

I suppose we could. Also realizing that `toString` is writing to `cout` rather than returning a `std::string` so going to change that as well.

**Review by squeeve — APPROVED** [review]
Clean execution, code looks good.

**Pull request merged**
